drop table if exists vacantes;

alter database postgres
set
  timezone to 'America/Bogota';

create table vacantes (
  id bigint generated by default as identity primary key,
  codigo text unique not null,
  cargo text,
  salario text,
  experiencia text,
  tipo_contrato text,
  teletrabajo text,
  ubicacion text,
  num_vacantes integer,
  num_postulaciones integer,
  fecha_publicacion timestamp with time zone,
  fecha_cierre timestamp with time zone,
  dias_restantes integer,
  url text,
  created_at timestamp with time zone default now()
);

alter table vacantes ENABLE row LEVEL SECURITY;

create extension IF not exists moddatetime SCHEMA extensions;

create trigger handle_updated_at BEFORE
update on vacantes for EACH row
execute PROCEDURE moddatetime (updated_at);

drop policy IF exists "Permitir todas las operaciones" on vacantes;

create policy "allow_public_all" on vacantes for all to public using (true)
with
  check (true);