DROP TABLE IF EXISTS vacantes;
alter database postgres set timezone to 'America/Bogota';
create table vacantes (
 id bigint generated by default as identity primary key,
 codigo text unique not null,
 cargo text,
 salario text,
 experiencia text,
 tipo_contrato text,
 teletrabajo text,
 ubicacion text, 
 num_vacantes integer,
 num_postulaciones integer,
 fecha_publicacion timestamp with time zone,
 fecha_cierre timestamp with time zone,
 dias_restantes integer,
 url text
);